# Generated by Django 3.2.25 on 2024-12-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sound', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sound', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='turtle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sound', models.CharField(max_length=20)),
            ],
        ),
    ]
