# Generated by Django 3.2.25 on 2024-12-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0002_bear_chicken_turtle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bear',
            old_name='image',
            new_name='img_b1',
        ),
    ]
